### ISSUE TITLE
frozen_inference_graph.pb; No such file or directory

### ISSUE THREAD

**Issue by prashant-bansod** [oulutan/ACAM_Demo#7]
@oulutan Thank you very much for sharing your work. This is the first of a kind of action recognition demo I have seen. I am trying to implement your code. I had a few issues while implementing the ` detect_actions.py `.  I will be grateful to you if you could give me some hints as a newbie in this domain. 
`/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
Loading object detection model at /home/oytun/work/Conditional_Attention_Maps_Demo/object_detection/weights/ssd_mobilenet_v2_coco_2018_03_29/frozen_inference_graph.pb
Traceback (most recent call last):
  File "detect_actions.py", line 312, in <module>
    main()
  File "detect_actions.py", line 52, in main
    obj_detector = obj.Object_Detector(obj_detection_graph)
  File "/home/prashantb/Documents/prashant_workspaace/ACAM_Demo/object_detection/object_detector.py", line 12, in __init__
    serialized_graph = fid.read()
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    self._preread_check()
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/oytun/work/Conditional_Attention_Maps_Demo/object_detection/weights/ssd_mobilenet_v2_coco_2018_03_29/frozen_inference_graph.pb; No such file or directory
`

**Comment by prashant-bansod** [comment]
for `multiprocess_detect_actions.py ` 
`/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
Reading video file sample_input.mp4
H: 720, W: 1280
Running actions every 8 frame
Writing output to ./output_videos/sample_input_output.mp4
Process Process-1:
Traceback (most recent call last):
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multiprocess_detect_actions.py", line 62, in read_frames
    for ii in range(nframes):
TypeError: 'float' object cannot be interpreted as an integer
Loading object detection model at ./object_detection/weights/ssd_mobilenet_v2_coco_2018_03_29/frozen_inference_graph.pb
Process Process-2:
Traceback (most recent call last):
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multiprocess_detect_actions.py", line 123, in run_obj_det_and_track_in_batches
    obj_detector = obj.Object_Detector(obj_detection_graph)
  File "/home/prashantb/Documents/prashant_workspaace/ACAM_Demo/object_detection/object_detector.py", line 12, in __init__
    serialized_graph = fid.read()
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    self._preread_check()
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./object_detection/weights/ssd_mobilenet_v2_coco_2018_03_29/frozen_inference_graph.pb; No such file or directory
/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/numpy/lib/type_check.py:546: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  'a.item() instead', DeprecationWarning, stacklevel=1)
2019-02-19 18:53:34.731027: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Using model soft_attn
2019-02-19 18:53:36.814128: W tensorflow/core/framework/allocator.cc:122] Allocation of 265420800 exceeds 10% of system memory.
2019-02-19 18:53:36.911601: W tensorflow/core/framework/allocator.cc:122] Allocation of 265420800 exceeds 10% of system memory.
2019-02-19 18:53:37.136869: W tensorflow/core/framework/allocator.cc:122] Allocation of 265420800 exceeds 10% of system memory.
2019-02-19 18:53:37.248810: W tensorflow/core/framework/allocator.cc:122] Allocation of 265420800 exceeds 10% of system memory.
2019-02-19 18:53:37.379403: W tensorflow/core/framework/allocator.cc:122] Allocation of 265420800 exceeds 10% of system memory.
Loading weights from ./action_detection/weights/model_ckpt_soft_attn_pooled_cosine_drop_ava-130
frame_q: 0, obj_q: 0, act_q: 0, vis_q: 0
Done!
`

**Comment by oulutan** [comment]
Thanks you! It looks like I forgot to change the paths in the simpler version. I will update it.

**Comment by prashant-bansod** [comment]
Thank you very much. I think the paths in the `object_detector.py` also need to be updated. 
```
from object_detection.deep_sort.tools.generate_detections import create_box_encoder
from object_detection.deep_sort.deep_sort import nn_matching
from object_detection.deep_sort.deep_sort.detection import Detection
from object_detection.deep_sort.deep_sort.tracker import Tracker as ds_Tracke
```
