### ISSUE TITLE
TypeError: only size-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by prashant-bansod** [oulutan/ACAM_Demo#9]
@oulutan I tried the `detect_actions.py` but it seems something went wrong. 
````
 python detect_actions.py --video_path sample_input.mp4 
/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
Loading object detection model at /home/prashantb/Documents/prashant_workspaace/ACAM_Demo/object_detection/weights/ssd_mobilenet_v2_coco_2018_03_29/frozen_inference_graph.pb
2019-02-20 15:40:08.703071: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Reading video file sample_input.mp4
Running actions every 8 frame
/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/numpy/lib/type_check.py:546: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  'a.item() instead', DeprecationWarning, stacklevel=1)
Using model soft_attn
Loading weights from ./action_detection/weights/model_ckpt_soft_attn_pooled_cosine_drop_ava-130
frame_cnt: 1
obj det 2.30 seconds
tracker 0.00 seconds
frame_cnt: 2
obj det 0.04 seconds
tracker 0.10 seconds
frame_cnt: 3
obj det 0.04 seconds
tracker 0.02 seconds
frame_cnt: 4
obj det 0.04 seconds
tracker 0.01 seconds
frame_cnt: 5
obj det 0.04 seconds
tracker 0.01 seconds
frame_cnt: 6
obj det 0.04 seconds
tracker 0.01 seconds
frame_cnt: 7
obj det 0.03 seconds
tracker 0.01 seconds
frame_cnt: 8
obj det 0.03 seconds
tracker 0.01 seconds
2019-02-20 15:40:15.682873: W tensorflow/core/framework/allocator.cc:122] Allocation of 353894400 exceeds 10% of system memory.
Person 1
	 stand: 0.201
	 walk: 0.173
	 watch (a person): 0.084
	 carry/hold (an object): 0.051
	 talk to (e.g., self, a person, a group): 0.031
action 2.96 seconds
frame_cnt: 9
obj det 0.03 seconds
tracker 0.01 seconds
frame_cnt: 10
obj det 0.03 seconds
tracker 0.01 seconds
frame_cnt: 11
obj det 0.03 seconds
tracker 0.01 seconds
frame_cnt: 12
obj det 0.03 seconds
tracker 0.01 seconds
frame_cnt: 13
obj det 0.03 seconds
tracker 0.01 seconds
frame_cnt: 14
obj det 0.03 seconds
tracker 0.01 seconds
frame_cnt: 15
obj det 0.04 seconds
tracker 0.01 seconds
frame_cnt: 16
obj det 0.03 seconds
tracker 0.01 seconds
2019-02-20 15:40:18.724569: W tensorflow/core/framework/allocator.cc:122] Allocation of 353894400 exceeds 10% of system memory.
Person 1
	 walk: 0.868
	 watch (a person): 0.176
	 carry/hold (an object): 0.102
	 stand: 0.096
	 talk to (e.g., self, a person, a group): 0.075
action 2.71 seconds
frame_cnt: 17
obj det 0.03 seconds
tracker 0.01 seconds
frame_cnt: 18
obj det 0.04 seconds
tracker 0.01 seconds
frame_cnt: 19
obj det 0.04 seconds
tracker 0.01 seconds
frame_cnt: 20
obj det 0.03 seconds
tracker 0.01 seconds
frame_cnt: 21
obj det 0.03 seconds
tracker 0.01 seconds
Traceback (most recent call last):
  File "detect_actions.py", line 314, in <module>
    main()
  File "detect_actions.py", line 182, in main
    out_img = visualize_detection_results(tracker.frame_history[-16], tracker.active_actors, prob_dict)
  File "detect_actions.py", line 244, in visualize_detection_results
    cv2.rectangle(disp_img, (left,top), (right,bottom), color, 3)
TypeError: only size-1 arrays can be converted to Python scalars
Fatal Python error: could not acquire lock for <_io.BufferedReader name=10> at interpreter shutdown, possibly due to daemon threads

Thread 0x00007fcb45de3700 (most recent call first):
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/imageio_ffmpeg/_parsing.py", line 61 in run
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007fcb86a8e700 (most recent call first):
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/subprocess.py", line 1537 in _communicate
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/subprocess.py", line 843 in communicate
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/imageio_ffmpeg/_io.py", line 189 in read_frames
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/imageio/plugins/ffmpeg.py", line 342 in _close
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/imageio/core/format.py", line 252 in close
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/imageio/core/format.py", line 241 in __del__
Aborted (core dumped)
```

**Comment by prashant-bansod** [comment]
@outlan Could you please upload the working code? Thank you. Sorry for the trouble.

**Comment by prashant-bansod** [comment]
@oulutan  I tried ` multiprocess_detect_actions.py`  I got the following output on the sample_video.mp4 
Could you please check? 
`python multiprocess_detect_actions.py --video_path sample_input.mp4
/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
Reading video file sample_input.mp4
H: 720, W: 1280
Running actions every 8 frame
Writing output to ./output_videos/sample_input_output.mp4
Loading object detection model at ./object_detection/weights/ssd_mobilenet_v2_coco_2018_03_29/frozen_inference_graph.pb
/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/numpy/lib/type_check.py:546: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  'a.item() instead', DeprecationWarning, stacklevel=1)
2019-02-20 17:03:23.811722: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-02-20 17:03:24.746611: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Using model soft_attn
Loading weights from ./action_detection/weights/model_ckpt_soft_attn_pooled_cosine_drop_ava-130
frame_q: 0, obj_q: 0, act_q: 0, vis_q: 0
Done!
`

**Comment by oulutan** [comment]
The code on the main branch works fine. This looks like it might be version issue with opencv. All of your pipeline works except the visualization. The code was tested on python 2.7.12 and opencv 3.3.0. It gives the error at [line](https://github.com/oulutan/ACAM_Demo/blob/56ad5709e1720e4e7f1c4e2414bcc0510ca0d9b4/detect_actions.py#L238), this is probably due to the color array. Your opencv version probably expects different type there. Try a tuple or a scalar for the color. If thats the issue following lines that use color will give errors as well.

**Comment by alike123** [comment]
I have the same problem.Have you solved it ?
